server:
  port: 8080
spring:
  application:
    name: spring-rest-security
  profiles:
    active: default
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: cihat
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    data: classpath:data.sql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: false
security:
  jwt:
    secret-key: cybertek





  spring.datasource.username=postgres
  spring.datasource.password=cihat
